# 问题
# - 计算周期
# - 计算峰-峰值
# - 计算修正值

name = "e_oscilloscope"

frequency = [50, 100, 200, 500]
complete_waves = [2, 4, 4, 2]
x_intervals = [8, 8, 10, 8]
time_konb_gear = [5.0, 5.0, 2.0, 0.5]

y_intervals = [4.5, 4.5, 4.5, 4.5]
voltage_konb_gear = [0.5, 0.5, 0.5, 0.5]

nodes_ratio = ["0.5", "2/3", "1", "1.5", "2"]
cal_vals = [25.0, 33.33, 50.0, 75.0, 100.0]
indicate_vals = [25.01, 33.37, 50.04, 75.03, 100.05]
