# 问题
# - 悬盘转动惯量测量值 J_tray = ( (m盘gRr) / (4(π^2)h) ) * (T_0)^2
# - 圆环转动惯量测量值 J_ring = ((m盘 + m环)gRr) / (4(π^2)h) ) * (T_10)^2 - J_tray
# - 空载转盘转动惯量理论值 J0 = 0.5 * m_tray * R^2
# - 空载圆盘转动惯量的实验误差百分量 E = (J_tray - J0) / J0 * 100%

name = "moment_of_inertia"

h_avg_cm = 47.60
a_avg_cm = 13.80
b_avg_cm = 7.99

# R = (sqrt(3)/3) * a
R = 7.97
# r = (sqrt(3)/3) * b
r = 4.61

m_tray_g = 602.24
m_ring_g = 231.32

T_i = [1.6756, 1.5890]
